import Head from 'next/head'
import Navbar from '../../components/Navbar'
import Login from '../../components/Login'

export default function LoginPage() {
  return (
    <div className='fixed  bg-gradient-to-t from-gray-300 via-white to-gray-300 top-0 h-screen bg w-screen overflow-hidden'>
      <Head>
        <title>E-Mediate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Login />
      </div>
  )
}