import Head from 'next/head'
import Navbar from '../../components/Navbar'
import Login from '../../components/Login'
import Footer from '../../components/Footer'

export default function LoginPage() {
  return (
    <div className='fixed font-Montserrat bg-hero-pattern  h-screen bg w-screen overflow-scroll'>
      <Head>
        <title>E-Mediate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Navbar />
      <Login />
      <Footer />
      </div>
  )
}